# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: dark  # Force dark mode instead of system settings
  color: emerald  # Keep or change to another accent color

# SEO
marketing:
  seo:
    site_type: SoftwareApplication  # More relevant for an app
    local_business_type: ''
    org_name: 'Bus Route Demand Visualiser'
    description: 'A web-based application for visualising origin-destination matrixes for the bus network of Singapore.'

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false  # Disable search if it's not needed
    show_theme_chooser: false  # Remove unnecessary customization
    logo:
      text: "Bus Route Demand Visualiser"

# Site footer
footer:
  copyright:
    notice: 'This app is property of STC. All rights reserved.'
    license:
      enable: false